name: Build static website
on: [push]
jobs:
  Build-Static-Pages:
    runs-on: ubuntu-latest
    steps:
      - name: update apt
        run: "apt-get update -yqqq"
      - name: install nodejs
        run: "apt-get install -y nodejs"
      - name: install ruby
        run: "apt-get install -y ruby-full"
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: install gems with bundle
        run: "bundle install --path vendor"
      - name: build the static site
        run: "bundle exec middleman build"
      - name: export the built site
        uses: actions/upload-artifact@v3
        with:
          name: tommymorgan.name
          path: public

